Repository TechNodes2-0/ElectiveHub, pull requests merged in 2023-10, with the labels that each got.

#6 Auto Login after signup
  .gitignore
  README.md
  client/.env
  client/.gitignore
  client/src/Components/Auth/Login.jsx
  client/src/Components/Auth/Signup.jsx
  client/src/Components/Navbar.jsx
  client/src/Pages/Home.jsx
  server/.env
Labels: review

#22 Created pull request template
  .github/pull_request_template.md
Labels: hacktoberfest, SLoP3-75, review

#21 Created issue templates
  .github/ISSUE_TEMPLATES/bug_report_v2.yml
  .github/ISSUE_TEMPLATES/documentation
  .github/ISSUE_TEMPLATES/enhancement_request.md
  .github/ISSUE_TEMPLATES/feature_request.md
  .github/ISSUE_TEMPLATES/miscellaneous.yml
  .github/ISSUE_TEMPLATES/questions
Labels: hacktoberfest, SLoP3-75, review

#17 Added filter Animation
  client/package.json
  client/src/Components/Student/StudentList.jsx
  client/src/Components/Subject/SubjectList.jsx
  client/src/Pages/StudentHome.jsx
  client/src/Pages/SubjectHome.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, SLoP3-25

#24 fix : the Issue Template
  .github/ISSUE_TEMPLATES/bug_report_v2.yml
  .github/ISSUE_TEMPLATES/bugs.yml
  .github/ISSUE_TEMPLATES/docs.yml
  .github/ISSUE_TEMPLATES/documentation
  .github/ISSUE_TEMPLATES/enhancement_request.md
  .github/ISSUE_TEMPLATES/featuer.yml
  .github/ISSUE_TEMPLATES/feature_request.md
  .github/ISSUE_TEMPLATES/miscellaneous.yml
  .github/ISSUE_TEMPLATES/questions
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#32 Update the project setup process in README & add `.env.example` files #31
  .env
  README.md
  client/.env.example
  server/.env.example
Labels: hacktoberfest, hacktoberfest-accepted, SLoP3-75

#35 Redirected the features tab to Login screen
  client/src/Components/Auth/Feature.jsx
Labels: hacktoberfest, SLoP3-75
